"""
Mode smoke test — validates that all three question modes
(retrieve, follow_up, clarify) are reachable and produce
correct question + feedback output.

The key design choice: responses are generated by the LLM for the ACTUAL
question retrieved, not hardcoded. Hardcoded responses are fragile because
the retrieved question is random within the topic — an overfitting response
to a confusion-matrix question will score 0 and trigger the wrong mode.

Three isolated sessions:

  Session 1 — follow_up
    LLM generates a partial, incomplete answer to the actual first question.
    Expected: score 3-6, covered non-empty, missed non-empty → follow_up.

  Session 2 — clarify  (two turns)
    Turn 1: partial answer → follow_up triggered, follow_up_count → 1.
    Turn 2: LLM generates comprehensive answer with ONE embedded misconception
            to the actual follow-up question.
    With follow_up_count=1 the condition `7.0 <= score < 8.0 and follow_ups < 1`
    is False, so clarify fires if misconceptions are detected and score >= 7.

  Session 3 — retrieve
    LLM generates a comprehensive, correct answer to the actual first question.
    Expected: score >= 8, no missed or misconceptions → retrieve.

Results are observational. Each session prints evaluation details so you can
diagnose unexpected modes.

Usage:
    python -m scripts.smoke_test_modes
"""

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from langchain_core.language_models import BaseChatModel
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver

from src.utils.config import get_settings
from src.utils.llm_factory import get_complex_llm, get_fast_llm
from src.utils.logging_config import get_logger
from src.rag.agentic_rag import AgenticRAGService
from src.rag.grader import DocumentGrader
from src.rag.query_refiner import QueryRefiner
from src.rag.cache import InterviewCacheStore
from src.rag.retriever import VectorRetriever
from src.data.vector_store import VectorStore
from src.tools.concept_lookup import initialize_concept_lookup
from src.graph.agent_registry import AgentRegistry
from src.graph.interview_graph import build_start_graph, build_interview_graph
from src.graph.state import initialize_state

logger = get_logger(__name__)

SEPARATOR = "─" * 60
FORCED_TOPIC = "machine_learning_fundamentals"


# ── Response generation prompts ───────────────────────────────────────────────
#
# These prompts are for TEST SCAFFOLDING only — they simulate candidates
# at different quality levels. Each receives the ACTUAL question text, so
# the generated response is always relevant regardless of what was retrieved.

_PARTIAL_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "You are simulating a candidate in a technical interview.\n"
     "Generate a response that is:\n"
     "- Relevant and on-topic to the question\n"
     "- Partially correct — mentions the concept but covers at most 1-2 key points\n"
     "- Clearly incomplete: misses most of the expected depth and detail\n"
     "- Brief: 2-4 sentences, no bullet points\n"
     "- No obvious factual errors — just shallow and incomplete\n"
     "Return ONLY the candidate response text, nothing else."),
    ("human", "Interview question: {question}")
])

# Two-step misconception injection.
# Step 1: extract a SPECIFIC wrong claim for this exact question (question-aware).
# Step 2: instruct the LLM to embed THAT EXACT claim in its response.
# Telling the LLM precisely what false statement to include is far more reliable
# than asking it to "come up with a misconception" — LLMs resist generating false
# claims unless given an explicit instruction with the exact text to embed.

_GET_MISCONCEPTION_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "You are an expert in machine learning and AI interviewing.\n"
     "For the given interview question, identify ONE common factual misconception "
     "that candidates hold about this specific topic.\n\n"
     "Requirements:\n"
     "- Clearly and objectively FALSE — not debatable or context-dependent\n"
     "- About a core concept directly in the question's scope\n"
     "- Something a candidate could genuinely believe by mistake\n\n"
     "Return ONLY a single sentence phrased as the wrong belief itself, "
     "as a candidate would state it (e.g. 'A higher R-squared always means a better model')."),
    ("human", "Interview question: {question}")
])

_EMBED_MISCONCEPTION_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "You are simulating a candidate in a technical interview.\n"
     "Write a comprehensive 5-8 sentence response to the question.\n\n"
     "You MUST include this specific claim in your answer: {misconception}\n"
     "Embed it naturally in the response as if you genuinely believe it — "
     "state it confidently, not hesitantly.\n"
     "The rest of your response should be technically correct.\n"
     "Return ONLY the response text, nothing else."),
    ("human", "Interview question: {question}")
])

_COMPREHENSIVE_PROMPT = ChatPromptTemplate.from_messages([
    ("system",
     "You are simulating a high-performing candidate in a technical interview.\n"
     "Generate a response that is:\n"
     "- Complete and technically accurate with no factual errors\n"
     "- Covers all major aspects: definition, mechanism, tradeoffs, examples\n"
     "- Well-structured: 8-12 sentences\n"
     "- Demonstrates genuine depth of understanding\n"
     "Return ONLY the candidate response text, nothing else."),
    ("human", "Interview question: {question}")
])


async def _generate_response(llm: BaseChatModel, prompt: ChatPromptTemplate, question: str) -> str:
    chain = prompt | llm | StrOutputParser()
    result = await chain.ainvoke({"question": question})
    return result.strip()


async def _generate_misconception_response(llm: BaseChatModel, question: str) -> tuple[str, str]:
    """
    Two-step misconception injection.

    Step 1: ask the LLM what a specific, objectively-false claim about this
            question's topic looks like. We capture the exact claim so we
            can print it for debugging and verify it was embedded.

    Step 2: instruct the LLM to write a comprehensive response that includes
            that EXACT claim. Providing the specific text is far more reliable
            than asking the LLM to "invent a misconception" — LLMs trained for
            accuracy resist generating wrong statements without explicit instruction.

    Returns: (response_text, embedded_misconception)
    """
    parser = StrOutputParser()
    misconception = (
        await (_GET_MISCONCEPTION_PROMPT | llm | parser).ainvoke({"question": question})
    ).strip()

    response = (
        await (_EMBED_MISCONCEPTION_PROMPT | llm | parser).ainvoke(
            {"question": question, "misconception": misconception}
        )
    ).strip()

    return response, misconception


# ── Print helpers ─────────────────────────────────────────────────────────────

def _print_section(title: str):
    print(f"\n{SEPARATOR}")
    print(f"  {title}")
    print(SEPARATOR)


def _print_question(label: str, q: dict):
    print(f"\n  ┌─ {label} {'─' * max(0, 47 - len(label))}")
    print(f"  │ {q.get('text', 'NO TEXT')}")
    print(
        f"  │ topic={q.get('topic')}  "
        f"difficulty={q.get('difficulty')}  "
        f"type={q.get('question_type')}"
    )
    print(f"  └{'─' * 52}")


def _print_response(label: str, response: str):
    print(f"\n  ┌─ {label} {'─' * max(0, 47 - len(label))}")
    for line in response.strip().splitlines():
        print(f"  │ {line.strip()}")
    print(f"  └{'─' * 52}")


def _print_feedback(text: str):
    print(f"\n  ┌─ FEEDBACK {'─' * 41}")
    print(f"  │ {text}")
    print(f"  └{'─' * 52}")


def _print_eval(ev: dict):
    print(f"\n  [Evaluation]")
    print(f"    overall_score  : {ev.get('overall_score')}")
    print(f"    is_fallback    : {ev.get('is_fallback')}")
    print(f"    covered        : {ev.get('key_points_covered', [])}")
    print(f"    missed         : {ev.get('key_points_missed', [])}")
    print(f"    misconceptions : {ev.get('misconceptions', [])}")


def _explain_miss(expected: str, actual: str):
    """Print diagnostics when the mode doesn't match."""
    print(f"\n  [DIAGNOSIS]")
    if expected == "follow_up":
        if actual == "follow_up":
            return
        if actual == "retrieve":
            print("  → score < 3.0 OR covered=[]: treated as off-topic → re-engagement path")
        elif actual == "clarify":
            print("  → score >= 7 but evaluator found misconceptions in the partial answer")

    elif expected == "clarify":
        if actual == "follow_up":
            print("  → Evaluator did not detect a misconception (misconceptions=[])")
            print("  → With no misconceptions, follow_up fires for incomplete answers")
            print("  → Check if the LLM-generated response embedded a clear enough error")
        elif actual == "retrieve":
            print("  → No misconceptions AND no gaps AND score >= 7 → retrieve")
            print("  → The LLM may have generated a clean response without any errors")

    elif expected == "retrieve":
        if actual == "follow_up":
            print("  → Score < 8 or 7-8 range with some missed points → follow_up")
        elif actual == "clarify":
            print("  → Evaluator found a misconception in the comprehensive response")
            print("  → Check if the LLM-generated answer contained an error")


# ── Turn runner ───────────────────────────────────────────────────────────────

async def _run_turn(
    interview_graph,
    seed_state: dict,
    candidate_response: str,
    session_id: str,
    turn_number: int,
    label: str,
) -> dict:
    config = RunnableConfig(
        configurable={"thread_id": session_id},
        metadata={"mode_test": label, "turn": turn_number},
        tags=["mode_smoke_test"],
    )
    return await interview_graph.ainvoke(
        {**seed_state, "candidate_response": candidate_response},
        config=config,
    )


# ── Session 1: follow_up ──────────────────────────────────────────────────────

async def run_session_follow_up(
    llm: BaseChatModel,
    agents, start_graph, interview_graph,
) -> dict:
    label = "Session 1 — FOLLOW_UP"
    _print_section(label)

    initial_state = initialize_state(
        difficulty="medium",
        time_budget_minutes=30,
        focus_topics=[FORCED_TOPIC],
    )
    session_id = initial_state["interview_id"]
    print(f"  session_id    : {session_id}")
    print(f"  expected mode : follow_up")

    start_result = await start_graph.ainvoke(
        initial_state,
        config=RunnableConfig(
            configurable={"thread_id": session_id},
            tags=["mode_smoke_test", "start"],
        ),
    )
    first_q = start_result.get("current_question", {})
    _print_question("FIRST QUESTION", first_q)

    print("\n  Generating partial response for this question...")
    response = await _generate_response(llm, _PARTIAL_PROMPT, first_q["text"])
    _print_response("PARTIAL RESPONSE (LLM-generated)", response)

    turn = await _run_turn(
        interview_graph, start_result, response, session_id, 1, label
    )

    ev = turn.get("current_evaluation", {})
    mode = turn.get("question_mode", "unknown")
    _print_eval(ev)
    _print_feedback(turn.get("current_feedback", "NO FEEDBACK"))
    print(f"\n  follow_up_count : {turn.get('follow_up_count', 0)}")
    print(f"  question_mode   : {mode}")
    if turn.get("current_question"):
        _print_question("NEXT QUESTION", turn["current_question"])

    passed = mode == "follow_up"
    status = "✓ PASS" if passed else "✗ FAIL"
    print(f"\n  [{status}]  expected=follow_up  actual={mode}")
    if not passed:
        _explain_miss("follow_up", mode)

    return {"label": label, "expected": "follow_up", "actual": mode, "passed": passed, "eval": ev}


# ── Session 2: clarify ───────────────────────────────────────────────────────

async def run_session_clarify(
    llm: BaseChatModel,
    agents, start_graph, interview_graph,
) -> dict:
    """
    Session 2 — clarify  (mocked evaluation)

    Why mocked evaluation:
    Getting the evaluator to reliably detect a misconception is not tractable.
    The LLM resists generating clearly-false statements, and even when it does,
    the evaluator only flags misconceptions that are squarely within the
    question's specific rubric scope — a wrong claim about a tangential concept
    is ignored. This is evaluator behaviour, not a clarify-mode bug.

    What we actually want to test here:
      - Given an evaluation that contains misconceptions, does the mode selector
        correctly choose "clarify"?
      - Does _generate_clarification produce a valid, relevant question?
      - Does the feedback agent produce appropriate feedback?

    Strategy:
      1. Run start_graph to get a real question (real retrieval, real plan).
      2. Inject a mocked evaluation with explicit misconceptions into the state.
      3. Call QuestionSelector and FeedbackAgent directly — no evaluator re-run.
      4. Assert mode == "clarify" and that a clarify question was generated.
    """
    label = "Session 2 — CLARIFY"
    _print_section(label)

    initial_state = initialize_state(
        difficulty="medium",
        time_budget_minutes=30,
        focus_topics=[FORCED_TOPIC],
    )
    session_id = initial_state["interview_id"]
    print(f"  session_id    : {session_id}")
    print(f"  expected mode : clarify")
    print(f"  strategy      : mocked evaluation with explicit misconceptions")
    print(f"                  → tests clarify logic without evaluator reliability risk")

    start_result = await start_graph.ainvoke(
        initial_state,
        config=RunnableConfig(
            configurable={"thread_id": session_id},
            tags=["mode_smoke_test", "start"],
        ),
    )
    first_q = start_result.get("current_question", {})
    _print_question("FIRST QUESTION", first_q)

    # Mocked candidate response — plausible but contains the injected wrong belief
    mock_response = (
        "I would explain model results by translating metrics into plain language. "
        "Instead of 'precision is 0.85', I would say '85% of flagged cases are real'. "
        "A model with high accuracy is always reliable for business use, regardless of "
        "class distribution or business context. Visual aids and storytelling help anchor "
        "findings in goals the business already cares about."
    )

    # Mocked evaluation — misconceptions explicitly set so the mode selector fires clarify.
    # The injected misconception ("high accuracy always means reliable") is a real, common
    # mistake that a clarify question should challenge.
    mock_eval = {
        "overall_score": 6.5,
        "technical_accuracy": {"score": 5.0, "reasoning": "Contains misconception about accuracy"},
        "completeness": {"score": 8.0, "reasoning": "Covers main communication points"},
        "depth": {"score": 7.0, "reasoning": "Adequate depth"},
        "clarity": {"score": 8.0, "reasoning": "Clear and structured"},
        "evaluation_reasoning": (
            "Response demonstrates good communication instincts but contains a clear "
            "misconception: claiming high accuracy always signals model reliability ignores "
            "class imbalance and the difference between technical and business performance."
        ),
        "key_points_covered": ["plain language translation", "business-relevant framing", "visual aids"],
        "key_points_missed": [],
        "misconceptions": [
            "A model with high accuracy is always reliable for business use regardless of "
            "class distribution or context — accuracy can be misleading on imbalanced datasets."
        ],
        "topic": first_q.get("topic", FORCED_TOPIC),
        "question_id": first_q.get("id", ""),
        "is_fallback": False,
        "needs_human_review": False,
        "consistency_divergence": None,
    }

    # Build the full state the agents need, extending start_result
    mocked_state = {
        **start_result,
        "candidate_response": mock_response,
        "current_evaluation": mock_eval,
        "follow_up_count": 0,
        "question_count": 0,
        "previous_feedback_structures": [],
        "recent_feedbacks": [],
    }

    print(f"\n  [Mocked evaluation injected]")
    _print_eval(mock_eval)
    _print_response("MOCKED CANDIDATE RESPONSE", mock_response)

    config = RunnableConfig(
        configurable={"thread_id": session_id},
        metadata={"mode_test": label},
        tags=["mode_smoke_test"],
    )

    # Call agents directly — skipping the evaluator re-run
    print("\n  Calling QuestionSelector with mocked evaluation...")
    qs_result = await agents.question_selector.execute(mocked_state, config)
    mode = qs_result.get("question_mode", "unknown")
    next_q = qs_result.get("current_question", {})

    print("  Calling FeedbackAgent with mocked evaluation...")
    fb_result = await agents.feedback.execute(mocked_state, config)
    feedback_text = fb_result.get("current_feedback", "NO FEEDBACK")

    print(f"\n  question_mode   : {mode}")
    if next_q:
        _print_question("CLARIFY QUESTION", next_q)
    _print_feedback(feedback_text)

    passed = mode == "clarify"
    status = "✓ PASS" if passed else "✗ FAIL"
    print(f"\n  [{status}]  expected=clarify  actual={mode}")
    if not passed:
        _explain_miss("clarify", mode)

    return {"label": label, "expected": "clarify", "actual": mode, "passed": passed, "eval": mock_eval}


# ── Session 3: retrieve ───────────────────────────────────────────────────────

async def run_session_retrieve(
    llm: BaseChatModel,
    agents, start_graph, interview_graph,
) -> dict:
    label = "Session 3 — RETRIEVE"
    _print_section(label)

    initial_state = initialize_state(
        difficulty="medium",
        time_budget_minutes=30,
        focus_topics=[FORCED_TOPIC],
    )
    session_id = initial_state["interview_id"]
    print(f"  session_id    : {session_id}")
    print(f"  expected mode : retrieve")

    start_result = await start_graph.ainvoke(
        initial_state,
        config=RunnableConfig(
            configurable={"thread_id": session_id},
            tags=["mode_smoke_test", "start"],
        ),
    )
    first_q = start_result.get("current_question", {})
    _print_question("FIRST QUESTION", first_q)

    print("\n  Generating comprehensive response for this question...")
    response = await _generate_response(llm, _COMPREHENSIVE_PROMPT, first_q["text"])
    _print_response("COMPREHENSIVE RESPONSE (LLM-generated)", response)

    turn = await _run_turn(
        interview_graph, start_result, response, session_id, 1, label
    )

    ev = turn.get("current_evaluation", {})
    mode = turn.get("question_mode", "unknown")
    _print_eval(ev)
    _print_feedback(turn.get("current_feedback", "NO FEEDBACK"))
    print(f"\n  follow_up_count : {turn.get('follow_up_count', 0)}")
    print(f"  question_mode   : {mode}")
    if turn.get("current_question"):
        _print_question("NEXT QUESTION", turn["current_question"])

    passed = mode == "retrieve"
    status = "✓ PASS" if passed else "✗ FAIL"
    print(f"\n  [{status}]  expected=retrieve  actual={mode}")
    if not passed:
        _explain_miss("retrieve", mode)

    return {"label": label, "expected": "retrieve", "actual": mode, "passed": passed, "eval": ev}


# ── Main ──────────────────────────────────────────────────────────────────────

async def main():
    settings = get_settings()

    print(f"\n{'═' * 60}")
    print("  AI INTERVIEW — MODE SMOKE TEST")
    print("  Tests: retrieve  |  follow_up  |  clarify")
    print(f"{'═' * 60}")
    print(f"  Primary LLM  : {settings.ollama_model}")
    print(f"  Secondary LLM: {settings.ollama_model_secondary}")
    print(f"  Focus topic  : {FORCED_TOPIC}")

    _print_section("Infrastructure")

    complex_llm = get_complex_llm()
    fast_llm = get_fast_llm()

    vector_store = VectorStore()
    retriever = VectorRetriever(vector_store)
    initialize_concept_lookup(retriever)

    available_topics = retriever.get_available_topics()
    print(f"  ✓ Available topics ({len(available_topics)}): {available_topics}")

    cache_store = InterviewCacheStore()
    grader = DocumentGrader(llm=fast_llm)
    refiner = QueryRefiner()
    rag_service = AgenticRAGService(
        retriever=retriever,
        grader=grader,
        refiner=refiner,
        cache_store=cache_store,
    )
    agents = AgentRegistry(
        complex_llm=complex_llm,
        fast_llm=fast_llm,
        rag_service=rag_service,
        cache_store=cache_store,
        available_topics=available_topics,
        consistency_samples=settings.consistency_samples,
    )
    print("  ✓ All agents ready")

    async with AsyncSqliteSaver.from_conn_string("mode_test_checkpoints.db") as checkpointer:
        start_graph = build_start_graph(agents, default_timeout=60.0)
        interview_graph = build_interview_graph(agents, checkpointer, default_timeout=60.0)

        kwargs = dict(
            llm=complex_llm,
            agents=agents,
            start_graph=start_graph,
            interview_graph=interview_graph,
        )

        results = [
            await run_session_follow_up(**kwargs),
            await run_session_clarify(**kwargs),
            await run_session_retrieve(**kwargs),
        ]

    # ── Summary ───────────────────────────────────────────────────────────────
    print(f"\n{'═' * 60}")
    print("  MODE TEST SUMMARY")
    print(f"{'═' * 60}")

    all_passed = True
    modes_seen = set(r["actual"] for r in results)

    for r in results:
        status = "✓ PASS" if r["passed"] else "✗ FAIL"
        print(
            f"  {status}  {r['label']:<30}  "
            f"expected={r['expected']:<10}  actual={r['actual']:<10}  "
            f"score={r['eval'].get('overall_score')}"
        )
        if not r["passed"]:
            all_passed = False

    all_modes = {"retrieve", "follow_up", "clarify"}
    missing = all_modes - modes_seen
    print(f"\n  Modes observed : {sorted(modes_seen)}")
    if missing:
        print(f"  Modes missing  : {sorted(missing)}  ← possible flow bug")
    else:
        print(f"  All three modes triggered at least once.")

    print()
    if all_passed:
        print(f"  ALL THREE MODE SESSIONS PASSED ✓")
    else:
        failed = [r["label"] for r in results if not r["passed"]]
        print(f"  SESSIONS WITH UNEXPECTED MODE: {failed}")
        print(
            f"  LLM evaluation scores drive mode selection. "
            f"Check [Evaluation] and [DIAGNOSIS] output above."
        )

    print(f"{'═' * 60}\n")


if __name__ == "__main__":
    asyncio.run(main())
